version: '3'
services:
 postgres:
  image: postgres:latest
  container_name: pgsql
  restart: always
  environment:
      POSTGRES_USER: c2ca
      POSTGRES_PASSWORD: c2cacool
  ports:
    - 5432:5432
  volumes:
    - /root/PostgreSQL/data:/var/lib/postgresql/data
