import ButtonAppBar from '@/component/navbar'
import '../globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Footer from '@/component/footer'
import { getServerSession } from 'next-auth'
import { authOptions }  from '../utils/authOptions'
import { redirect } from 'next/navigation'
import styles from "../page.module.css";


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  // Verify the session role, before giving access
  const session = await getServerSession(authOptions);
  if (!(session?.user.role === "admin")) {
    redirect("/unauthorized");
  }
  if (!(session)) {
    redirect("/api/auth/signin");
  }
  return (
    <html lang="en">
        <body className={inter.className}>
          <ButtonAppBar/>
          <main className={styles.main}>
          {children}
          </main>
          <Footer/>

        </body>
    </html>
  )
}
